require("core.plugin_config.mason")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.dap_config")
require("core.plugin_config.rust_config")
require("core.plugin_config.nvim-metals")
