require("core.plugin_config.moonlight")
require("core.plugin_config.treesitter")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_zero")
require("core.plugin_config.lspsaga")
require("core.plugin_config.gitsigns")
